services:
    web_blue:
        build:
            context: .
            dockerfile: ${DOCKERFILE}
            args:
               CACHEBUST: ${CACHEBUST:-$(date +%s)}
               DOCKER_AWS_ACCESS_KEY_ID: ${DOCKER_AWS_ACCESS_KEY_ID}
               DOCKER_AWS_SECRET_ACCESS_KEY: ${DOCKER_AWS_SECRET_ACCESS_KEY}
            no_cache: true
        image: wedlock-frontend:blue
        container_name: wedlock-frontend-blue
        ports:
            - '5173:5173'
        networks:
            - backend
        restart: always
        env_file:
            - .env
        environment:
            - TZ=Asia/Kolkata
        healthcheck:
          test: ["CMD", "curl", "-f", "http://localhost:5173/health"]
          interval: 10s
          timeout: 5s
          retries: 5
          start_period: 10s

networks:
    backend:
        external: true