services:
    web_green:
        build:
            context: .
            dockerfile: ${DOCKERFILE}
        image: vedvivah-frontend:green
        container_name: vedvivah-frontend-green
        ports:
            - '5174:5173'
        networks:
            - backend
        restart: always
        env_file:
            - .env
        environment:
            - TZ=Asia/Kolkata
        healthcheck:
          test: ["CMD", "curl", "-f", "http://localhost:5173/health"]
          interval: 10s
          timeout: 5s
          retries: 5
          start_period: 10s
networks:
    backend:
        external: true